openapi: 3.1.0
info:
  version: 1.0.0
  title: Назва вашого додатку
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Опис вашого додатку
tags:
  - name: Contacts
    description: Ендпоінти для керування контактами
servers:
  - url: http://localhost:3000
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
